# -*- coding: utf-8 -*-
"""NguyenHoangPhuc_TH_TTNT_CN_T1_BTVN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dn4NDx8tGTzovRHhNDkS4IIERxEObVvd
"""

# Bài 1:
#nhập mảng
def nhap_mang_1d(ten_mang):
    s = input(f"Nhập các phần tử của {ten_mang} (cách nhau bởi khoảng trắng): ")
    return [int(x) for x in s.split()]

#chọn Min
def tron_mang_min(a, b):
    res = []
    n1, n2 = len(a), len(b)
    for i in range(max(n1, n2)):
        if i < n1 and i < n2:
            res.append(min(a[i], b[i]))
        elif i < n1:
            res.append(a[i])
        else:
            res.append(b[i])
    return res

# Run
mang_a = nhap_mang_1d("mảng a")
mang_b = nhap_mang_1d("mảng b")
print(f"Kết quả (lấy Min): {tron_mang_min(mang_a, mang_b)}")

# Bài 2:
import numpy as np

def nhap_ma_tran_vuong():
    n = int(input("Nhập cấp của ma trận vuông n: "))
    matrix = []
    for i in range(n):
        row = list(map(int, input(f"Nhập dòng {i} (gồm {n} số, cách nhau bởi khoảng trắng): ").split()))
        while len(row) != n:
            row = list(map(int, input(f"Sai số lượng! Nhập lại dòng {i}: ").split()))
        matrix.append(row)
    return np.array(matrix), n

a, n = nhap_ma_tran_vuong()
print("Ma trận bạn vừa nhập:\n", a)


# a. Tổng tam giác trên đ/c phụ (i + j <= n - 1)
tong_tren_phu = sum(a[i, j] for i in range(n) for j in range(n) if i + j <= n - 1)
print(f"a. Tổng tam giác trên đường chéo phụ: {tong_tren_phu}")

# b. Trị tuyệt đối
print("b. Trị tuyệt đối:\n", np.abs(a))

# c. Thay chẵn bằng x
x = int(input("c.	Chọn số nguyên x thay vào các phần tử chẵn : "))
a_c = a.copy()
a_c[a_c % 2 == 0] = x
print(f"c. Đã thay số chẵn trong ma trận bằng {x}:\n", a_c)

# d. Kiểm tra ma trận toàn chẵn
is_all_even = True
for i in range(n):
    for j in range(n):
        if a[i][j] % 2 != 0:
            is_all_even = False
            break
    if not is_all_even: break
print(f"d. Ma trận ban đầu {'Toàn chẵn' if is_all_even else 'Không toàn chẵn'}")

# e. Kiểm tra ma trận đối xứng
is_symmetric = True
for i in range(n):
    for j in range(i + 1, n):
        if a[i][j] != a[j][i]:
            is_symmetric = False
            break
    if not is_symmetric: break
print(f"e. Ma trận ban đầu {'Đối xứng' if is_symmetric else 'Không đối xứng'}")

# f. Kiểm tra đường chéo chính
is_diag_inc = True
for i in range(n - 1):
    if a[i][i] >= a[i+1][i+1]:
        is_diag_inc = False
        break
print(f"f. Ma trận ban đầu có đường {'Chéo chính tăng dần' if is_diag_inc else 'Chéo chính không tăng dần'}")

# g. Xuất tam giác dưới đ/c phụ (i + j >= n - 1)
print("g. Các phần tử tam giác dưới đường chéo phụ:")
for i in range(n):
    for j in range(n):
        if i + j >= n - 1:
            print(a[i, j], end=" ")
print()

# h. Kiểm tra đường chéo phụ giảm dần
is_sub_dec = True
for i in range(n - 1):
    if a[i][n-1-i] <= a[i+1][n-1-(i+1)]:
        is_sub_dec = False
        break
print(f"h. Ma trận ban đầu có đường {'Chéo phụ giảm dần' if is_sub_dec else 'Chéo phụ không giảm dần'}")

# Bài 3

# Dictionary quản lý cửa hàng điện thoại
cua_hang = {
    "iphone": {"ten": "iPhone 15 Pro", "gia": 28000000, "ton_kho": 10},
    "samsung": {"ten": "Samsung S24 Ultra", "gia": 26000000, "ton_kho": 5},
    "xiaomi": {"ten": "Xiaomi 14", "gia": 18000000, "ton_kho": 20}
}

# Xuất thông tin
for hang, thong_tin in cua_hang.items():
    print(f"-Hãng máy: {hang.upper()}")
    print(f" + Tên máy: {thong_tin['ten']}")
    print(f" + Giá bán: {thong_tin['gia']:,} VNĐ")
    print(f" + Tồn kho: {thong_tin['ton_kho']} chiếc")

# Bài 4

file_name = "bai_hat.txt"
# 1. Ghi file
noi_dung_ghi = "\nTừ nơi....\nđồng xanh thơm hương lúa!"
with open(file_name, "w", encoding="utf-8") as f:
    f.write(noi_dung_ghi)
print(f"--- Đã xuất nội dung vào file '{file_name}'")

# 2. Đọc file và in ra màn hình
print("-Nội dung đọc được từ file:")
with open(file_name, "r", encoding="utf-8") as f:
    for line in f:
        print(line.strip())

# Bài 5
import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Tên': ['An', 'Bình', 'Chi', 'Dũng', 'Ngân'],
    'Điểm Toán': [8.5, 7.0, 9.5, 6.5, 8.0],
    'Điểm Lý': [7.5, 8.0, 9.0, 7.0, 8.5]
}
df = pd.DataFrame(data)

print("Bảng điểm môn Toán và Lý:")
print(df)
print("-" * 30)

plt.figure(figsize=(8, 5))

plt.bar(df['Tên'], df['Điểm Toán'], width=0.4, label='Toán', align='center', color='skyblue')
plt.bar(df['Tên'], df['Điểm Lý'], width=0.4, label='Lý', align='edge', color='orange')

plt.title('Biểu đồ so sánh điểm Toán và Lý')
plt.xlabel('Tên học sinh')
plt.ylabel('Thang điểm 10')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

# THUẬT GIẢI AKT & A*

# Bài 1(Tại lớp)

import copy
from queue import PriorityQueue

# Cấu hình bàn cờ 4x4
N = 4
goal_state = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 0] # 0 đại diện cho ô trống
]

class State:
    def __init__(self, data, g=0, h=0, parent=None):
        self.data = data
        self.g = g # Số bước đã đi
        self.h = h # Ước tính số bước còn lại
        self.f = g + h # Tổng chi phí AKT
        self.parent = parent

    def __lt__(self, other):
        return self.f < other.f

# Đếm số ô sai vị trí so với đích
def calculate_h(current, goal):
    count = 0
    for i in range(N):
        for j in range(N):
            if current[i][j] != 0 and current[i][j] != goal[i][j]:
                count += 1
    return count

def find_blank(data):
    for i in range(N):
        for j in range(N):
            if data[i][j] == 0: return i, j

def move(data, r1, c1, r2, c2):
    new_data = copy.deepcopy(data)
    new_data[r1][c1], new_data[r2][c2] = new_data[r2][c2], new_data[r1][c1]
    return new_data

def print_path(node):
    path = []
    curr = node
    while curr:
        path.append(curr.data)
        curr = curr.parent
    path.reverse()

    print(f"=== KẾT QUẢ TÌM KIẾM AKT ===")
    print(f"Tổng số bước di chuyển tối ưu: {len(path) - 1}")
    for step, matrix in enumerate(path):
        print(f"\n[Bước {step}]")
        for row in matrix:
            print(" ".join(f"{x:2}" if x != 0 else " _" for x in row))
    print("\n=> Kết luận: đã tìm ra đường đi ngắn nhất bằng các trạng thái có ít ô sai nhất.")

def solve_15_puzzle(initial_matrix):
    start_node = State(initial_matrix)
    start_node.h = calculate_h(initial_matrix, goal_state)

    open_list = PriorityQueue()
    open_list.put(start_node)
    closed_list = set()

    while not open_list.empty():
        current = open_list.get()

        if current.data == goal_state:
            return current

        state_tuple = tuple(tuple(row) for row in current.data)
        if state_tuple in closed_list: continue
        closed_list.add(state_tuple)

        r, c = find_blank(current.data)
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < N and 0 <= nc < N:
                child_data = move(current.data, r, c, nr, nc)
                h = calculate_h(child_data, goal_state)
                child_node = State(child_data, current.g + 1, h, current)
                open_list.put(child_node)
    return None

test_data = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 0, 14, 15]
]
res = solve_15_puzzle(test_data)
if res: print_path(res)

# Bài 2(Tại lớp)
def a_star_search(graph, heuristics, start, goal):
    open_list = {start}
    closed_list = set()

    g = {start: 0}
    parents = {start: start}

    while open_list:
        # Chọn đỉnh n có f(n) = g(n) + h(n) nhỏ nhất
        n = min(open_list, key=lambda v: g[v] + heuristics[v])

        if n == goal:
            path = []
            while parents[n] != n:
                path.append(n)
                n = parents[n]
            path.append(start)
            path.reverse()

            print(f"=== KẾT QUẢ TÌM KIẾM A* ===")
            print(f"Đường đi tìm được: {' -> '.join(path)}")
            print(f"Tổng chi phí thực tế: {g[goal]}")
            print("\n=> Kết luận: Thuật giải A* đảm bảo tìm được đường đi ngắn nhất nhờ kết hợp giữa chi phí đã đi và ước lượng tương lai.")
            return path

        for (m, weight) in graph.get(n, []):
            if m not in open_list and m not in closed_list:
                open_list.add(m)
                parents[m] = n
                g[m] = g[n] + weight
            else:
                if g[m] > g[n] + weight:
                    g[m] = g[n] + weight
                    parents[m] = n
                    if m in closed_list:
                        closed_list.remove(m)
                        open_list.add(m)

        open_list.remove(n)
        closed_list.add(n)

    print("Không tìm thấy đường đi!")
    return None

# Dữ liệu mẫu: Đồ thị kề (Đỉnh: [(Đỉnh kề, Trọng số),...])
graph_data = {
    'A': [('B', 1), ('C', 3)],
    'B': [('D', 2)],
    'C': [('D', 1)],
    'D': [('E', 5)],
    'E': []
}

# Hàm Heuristic
h_table = {
    'A': 6,
    'B': 4,
    'C': 4,
    'D': 2,
    'E': 0
}

# Thực thi
a_star_search(graph_data, h_table, 'A', 'E')

import heapq
import time

class PuzzleSolver:
    def __init__(self, n, initial_state):
        self.n = n
        self.start = initial_state
        self.goal = self._generate_goal(n)

        self.goal_pos = {self.goal[r][c]: (r, c) for r in range(n) for c in range(n)}

    def _generate_goal(self, n):
        """Tạo ma trận đích: 1, 2, 3... (n*n-1), 0"""
        flat_goal = list(range(1, n*n)) + [0]
        return [flat_goal[i:i+n] for i in range(0, len(flat_goal), n)]

    def manhattan(self, state):
        """Quy trình tính tổng khoảng cách Manhattan cho toàn bảng"""
        dist = 0
        for r in range(self.n):
            for c in range(self.n):
                val = state[r][c]
                if val != 0:
                    target_r, target_c = self.goal_pos[val]
                    dist += abs(r - target_r) + abs(c - target_c)
        return dist

    def solve(self):
        # (f, g, current_state, path_history)
        h_start = self.manhattan(self.start)
        # Lưu path dưới dạng list các ma trận
        pq = [(h_start, 0, self.start, [])]
        visited = set()

        start_time = time.time()

        while pq:
            f, g, curr, path = heapq.heappop(pq)

            if curr == self.goal:
                return path + [curr], time.time() - start_time

            state_tuple = tuple(tuple(row) for row in curr)
            if state_tuple in visited: continue
            visited.add(state_tuple)

            r, c = next((r, c) for r in range(self.n) for c in range(self.n) if curr[r][c] == 0)

            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if 0 <= nr < self.n and 0 <= nc < self.n:

                    new_state = [list(row) for row in curr]
                    new_state[r][c], new_state[nr][nc] = new_state[nr][nc], new_state[r][c]

                    if tuple(tuple(row) for row in new_state) not in visited:
                        h = self.manhattan(new_state)
                        heapq.heappush(pq, (g + 1 + h, g + 1, new_state, path + [curr]))
        return None, 0

def hien_thi_lo_trinh(path, n):
    if not path:
        print("Không tìm thấy lời giải!")
        return

    print(f"Bài toán cần: {len(path)-1} bước di chuyển")
    print("-" * 30)
    for i, step in enumerate(path):
        print(f"BƯỚC {i}:")
        for row in step:
            print(" ".join(f"{val:2}" if val != 0 else " _" for val in row))
        print()

# --- THỰC THI
N_SIZE = 5
initial_5x5 = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 0, 24]
]

solver = PuzzleSolver(N_SIZE, initial_5x5)
result_path, duration = solver.solve()
hien_thi_lo_trinh(result_path, N_SIZE)
print(f"⏱️ Thời gian xử lý: {duration:.10f} giây")

# Bài 2(về nhà)
import heapq

def giai_tsp_astar(matrix, start_node=0):
    n = len(matrix)

    min_edge = min(matrix[i][j] for i in range(n) for j in range(n) if i != j)

    pq = [(0, 0, start_node, 1 << start_node, [start_node])]

    visited_costs = {}

    print(f"--- BẮT ĐẦU TÌM KIẾM LỘ TRÌNH TỪ THÀNH PHỐ {start_node} ---")

    while pq:
        f, g, u, mask, path = heapq.heappop(pq)

        if mask == (1 << n) - 1:
            total_path = path + [start_node]
            total_cost = g + matrix[u][start_node]

            print("\nLỘ TRÌNH TỐI ƯU:")
            print(f"- Lộ trình di chuyển: {' -> '.join(map(str, total_path))}")
            print(f"- Tổng chi phí: {total_cost}")
            return total_path, total_cost

        state = (u, mask)
        if state in visited_costs and visited_costs[state] <= g:
            continue
        visited_costs[state] = g

        for v in range(n):
            if not (mask & (1 << v)):
                new_g = g + matrix[u][v]

                remaining_cities = n - bin(mask).count('1')
                h = remaining_cities * min_edge

                new_f = new_g + h
                heapq.heappush(pq, (new_f, new_g, v, mask | (1 << v), path + [v]))

# --- Dữ liệu đầu vào: Ma trận chi phí giữa 5 thành phố ---
khoang_cach = [
    [0, 10, 15, 20, 25],
    [10, 0, 35, 25, 30],
    [15, 35, 0, 30, 5],
    [20, 25, 30, 0, 15],
    [25, 30, 5, 15, 0]
]

giai_tsp_astar(khoang_cach)